/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202303260949.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_MOSI_MOSC_Infotainment_Bridge_PROXY_HPP_
#define V1_COM_MOSI_MOSC_Infotainment_Bridge_PROXY_HPP_

#include <v1/com/mosi/mosc/InfotainmentBridgeProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace mosi {
namespace mosc {

template <typename ... _AttributeExtensions>
class InfotainmentBridgeProxy
    : virtual public InfotainmentBridge,
      virtual public InfotainmentBridgeProxyBase,
      virtual public _AttributeExtensions... {
public:
    InfotainmentBridgeProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~InfotainmentBridgeProxy();

    typedef InfotainmentBridge InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Returns the wrapper class that provides access to the attribute serviceStatus.
     */
    virtual ServiceStatusAttribute& getServiceStatusAttribute() {
        return delegate_->getServiceStatusAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast songDetail.
     */
    virtual SongDetailEvent& getSongDetailEvent() {
        return delegate_->getSongDetailEvent();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast currentProgress.
     */
    virtual CurrentProgressEvent& getCurrentProgressEvent() {
        return delegate_->getCurrentProgressEvent();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast playStatus.
     */
    virtual PlayStatusEvent& getPlayStatusEvent() {
        return delegate_->getPlayStatusEvent();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast tbtInfo.
     */
    virtual TbtInfoEvent& getTbtInfoEvent() {
        return delegate_->getTbtInfoEvent();
    }
    /**
     * Returns the wrapper class that provides access to the broadcast controlPage.
     */
    virtual ControlPageEvent& getControlPageEvent() {
        return delegate_->getControlPageEvent();
    }



 private:
    std::shared_ptr< InfotainmentBridgeProxyBase> delegate_;
};

typedef InfotainmentBridgeProxy<> InfotainmentBridgeProxyDefault;

namespace InfotainmentBridgeExtensions {
    template <template <typename > class _ExtensionType>
    class ServiceStatusAttributeExtension {
     public:
        typedef _ExtensionType< InfotainmentBridgeProxyBase::ServiceStatusAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< InfotainmentBridgeProxyBase::ServiceStatusAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        ServiceStatusAttributeExtension(InfotainmentBridgeProxyBase& proxy): attributeExtension_(proxy.getServiceStatusAttribute()) {
        }
    
        inline extension_type& getServiceStatusAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace InfotainmentBridgeExtensions

//
// InfotainmentBridgeProxy Implementation
//
template <typename ... _AttributeExtensions>
InfotainmentBridgeProxy<_AttributeExtensions...>::InfotainmentBridgeProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< InfotainmentBridgeProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< InfotainmentBridgeProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
InfotainmentBridgeProxy<_AttributeExtensions...>::~InfotainmentBridgeProxy() {
}


template <typename ... _AttributeExtensions>
const CommonAPI::Address &InfotainmentBridgeProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool InfotainmentBridgeProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool InfotainmentBridgeProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& InfotainmentBridgeProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& InfotainmentBridgeProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> InfotainmentBridgeProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace mosc
} // namespace mosi
} // namespace com
} // namespace v1

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v1::com::mosi::mosc::InfotainmentBridgeProxy,
    _AttributeExtension> {
    typedef typename ::v1::com::mosi::mosc::InfotainmentBridgeProxy<
            ::v1::com::mosi::mosc::InfotainmentBridgeExtensions::ServiceStatusAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_MOSI_MOSC_Infotainment_Bridge_PROXY_HPP_
