/*
* This file was generated by the CommonAPI Generators.
* Used com.fawvw.commonapi.fdbus 0.1.0.v202306290745.
* Used org.franca.core 0.13.1.201807231814.
*
*/

#ifndef V1_COM_MOSI_MOSC_COMMON_TYPES_FDBUS_DEPLOYMENT_HPP_
#define V1_COM_MOSI_MOSC_COMMON_TYPES_FDBUS_DEPLOYMENT_HPP_

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif
#include <CommonAPI/FDBus/FDBusDeployment.hpp>
#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace mosi {
namespace mosc {
namespace CommonTypes_ {

// typecollection-specific deployment types

// typecollection-specific deployments

} // namespace CommonTypes_
} // namespace mosc
} // namespace mosi
} // namespace com
} // namespace v1

#endif // V1_COM_MOSI_MOSC_COMMON_TYPES_FDBUS_DEPLOYMENT_HPP_
