/*
* This file was generated by the CommonAPI Generators.
* Used com.fawvw.commonapi.fdbus 0.1.0.v202306290745.
* Used org.franca.core 0.13.1.201807231814.
*
*/
#include "CommonTypesFDBusDeployment.hpp"

namespace v1 {
namespace com {
namespace mosi {
namespace mosc {
namespace CommonTypes_ {

// typecollection-specific deployments

} // namespace CommonTypes_
} // namespace mosc
} // namespace mosi
} // namespace com
} // namespace v1
