/*
* This file was generated by the CommonAPI Generators.
* Used com.fawvw.commonapi.fdbus 0.1.0.v202306290745.
* Used org.franca.core 0.13.1.201807231814.
*
*/
#include "InfotainmentBridgeFDBusDeployment.hpp"

namespace v1 {
namespace com {
namespace mosi {
namespace mosc {
namespace InfotainmentBridge_ {

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployments

// Broadcast-specific deployments

} // namespace InfotainmentBridge_
} // namespace mosc
} // namespace mosi
} // namespace com
} // namespace v1
