/*
* This file was generated by the CommonAPI Generators.
* Used com.fawvw.commonapi.fdbus 0.1.0.v202306290745.
* Used org.franca.core 0.13.1.201807231814.
*
*/

#ifndef V1_COM_MOSI_MOSC_Infotainment_Bridge_FDBUS_DEPLOYMENT_HPP_
#define V1_COM_MOSI_MOSC_Infotainment_Bridge_FDBUS_DEPLOYMENT_HPP_

#include <v1/com/mosi/mosc/InfotainmentBridgeFDBusDeployment.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif
#include <CommonAPI/FDBus/FDBusDeployment.hpp>
#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace mosi {
namespace mosc {
namespace InfotainmentBridge_ {

// Interface-specific deployment types
typedef CommonAPI::FDBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> PlayStatusDeployment_t;

typedef CommonAPI::FDBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::FDBus::StringDeployment,
    CommonAPI::FDBus::StringDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> SongDeployment_t;

typedef CommonAPI::FDBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment
> ProgressDeployment_t;

typedef CommonAPI::FDBus::StructDeployment<
    CommonAPI::FDBus::IntegerDeployment,
    CommonAPI::FDBus::IntegerDeployment,
    CommonAPI::FDBus::StringDeployment,
    CommonAPI::FDBus::StringDeployment
> TbtDeployment_t;


// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployments

// Broadcast-specific deployments


} // namespace InfotainmentBridge_
} // namespace mosc
} // namespace mosi
} // namespace com
} // namespace v1

#endif // V1_COM_MOSI_MOSC_Infotainment_Bridge_FDBUS_DEPLOYMENT_HPP_
